Created wrapper to hold img ratio same as PromoEventCard
bratislava/mestskakniznica.sk pull request #297
Opened 2023-12-15 12:35 UTC by ValkovMirec

- calculated ration on example card 
- created wrapper arround images where needed to hold that ratio
- done TODO in notice card: Use "MImage" component

2023-12-15 15:34 UTC, radoslavzeman requested changes
Yes, image probably needs a wrapping div, but your implementation is not responsive and removes placeholder for NoticeCard.

You can use MImage in both cases, it's even better.

2023-12-15 15:34 UTC, radoslavzeman commented on next/modules/cards-and-rows/EventCard.tsx
> +      </div>
Never use fixed width for cards, they must be responsive.

`object-cover` is usually used on Image together with `fill`:
```
<Image fill className="object-cover" .../>
```

Try to use tailwind's `aspect-ratio` class.

2023-12-15 15:34 UTC, radoslavzeman commented on next/modules/cards-and-rows/NoticeCard.tsx
> +        )}
This will not show Placeholder if no image is provided...

See also comments above.

2023-12-19 11:15 UTC, daksas303 commented
- Removed fixed width
- Added `fallbackImage` into next image `onError` when failed to load image src into `MImage`. Note: There appears to be an issue when having opened Chrome dev tools, that the images randomly flicker (on load, on scroll, etc.). With Chrome dev tools closed it behaves normally, but in case this appears as an issue we will have to figure out a different solution.
- Added object-cover
- Tried the tailwinds aspect ration but it didn't seem to make a difference.

2024-12-13 03:19 UTC, closed without merging